= Extractor
* Create a Maven project. Use `groupId` `io.github.oliviercailloux` (or your own group id) and `artifactId` `extractor-` followed by your GitHub username.
* Create a repository for your exercice https://classroom.github.com/a/Ny5sBwFU[here]. Clone it and move your just created Maven project into the root of this folder.
* This project will build a simple class that is able to extract plain text from a PDF. For this, we will use Apache https://pdfbox.apache.org/[PDFBox]. Add the required dependency to your POM.
* There is a file already in your repository. It defines an interface `SimpleExtractor`. Move this file in the right folder, corresponding to its declared package (do not change its package).
* Now your project should compile (and do nothing). Commit your code so far.
* Implement the interface in a class `MySimpleExtractor`. Its package should be your group id, followed by your artifact id, with hyphens replaced by underscores (following the Maven https://github.com/oliviercailloux/java-course/blob/master/Best%20practices/Maven.adoc[Best practices])
** Tips: to use PDFBox to extract text from a PDF, you only need to deal with two PDFBox classes: `PDDocument` and `PDFTextStripper`. Keep it simple: only a few lines of code are necessary to implement each method in `SimpleExtractor`. Remember you can use a `StringWriter` to write in memory.
** The method `getAllText` should return an https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/ImmutableList.html[`ImmutableList`]. (You will get two third of the mark if you return a normal list.)
** You can use http://www.xmlpdf.com/manualfiles/hello-world.pdf[this] PDF if you want to test your code. The extracted test should be `hello world\n`.

_Important_: Make sure your code compiles (according to `mvn compile`). Otherwise, almost no points will be granted. If you don’t know how to implement some method, at least write a minimal code that satisfies your compiler.

Here is a list of criteria that your code should satisfy.

* You committed around or before half-time (in supplement to your last commit)
* Your pom is at the root of your repository
* Your methods must fail if an exception is thrown at any point during execution of the code.
* POM satisfies the best practices
* Dependencies in the POM (to PDFBox and Guava) are well configured
* `groupId`, `artifactId`, package are chosen wisely and according to instructions
* All `Closable` objects you create must be correctly closed
* Implementation of `SimpleExtractor` must satisfy its contract
* Your code in your last commit counts, not the code committed earlier

Time allowed: 40 minutes.

* Late: −0.05/20 per second. (Timestamp given by GitHub server.)

